// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals

#include "verilated_vcd_c.h"
#include "Vtop__Syms.h"


void Vtop___024root__trace_chg_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp);

void Vtop___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_chg_0\n"); );
    // Body
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    if (VL_UNLIKELY(!vlSymsp->__Vm_activity)) return;
    Vtop___024root__trace_chg_0_sub_0((&vlSymsp->TOP), bufp);
}

void Vtop___024root__trace_chg_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_chg_0_sub_0\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode + 0);
    bufp->chgBit(oldp+0,(vlSelfRef.clk));
    bufp->chgBit(oldp+1,(vlSelfRef.reset));
    bufp->chgBit(oldp+2,(vlSelfRef.Top__DOT__clk));
    bufp->chgBit(oldp+3,(vlSelfRef.Top__DOT__reset));
    bufp->chgBit(oldp+4,(vlSelfRef.Top__DOT__memWrite));
    bufp->chgIData(oldp+5,(vlSelfRef.Top__DOT__mem_addr),32);
    bufp->chgIData(oldp+6,(vlSelfRef.Top__DOT__mem_wdata),32);
    bufp->chgCData(oldp+7,(vlSelfRef.Top__DOT__mem_wmask),4);
    bufp->chgIData(oldp+8,(vlSelfRef.Top__DOT__mem_rdata),32);
    bufp->chgBit(oldp+9,(vlSelfRef.Top__DOT__cpu__DOT__clk));
    bufp->chgBit(oldp+10,(vlSelfRef.Top__DOT__cpu__DOT__reset));
    bufp->chgBit(oldp+11,(vlSelfRef.Top__DOT__cpu__DOT__memWrite));
    bufp->chgIData(oldp+12,(vlSelfRef.Top__DOT__cpu__DOT__mem_rdata),32);
    bufp->chgIData(oldp+13,(vlSelfRef.Top__DOT__cpu__DOT__mem_addr),32);
    bufp->chgIData(oldp+14,(vlSelfRef.Top__DOT__cpu__DOT__mem_wdata),32);
    bufp->chgCData(oldp+15,(vlSelfRef.Top__DOT__cpu__DOT__mem_wmask),4);
    bufp->chgBit(oldp+16,(vlSelfRef.Top__DOT__cpu__DOT__zero));
    bufp->chgIData(oldp+17,(vlSelfRef.Top__DOT__cpu__DOT__instruction),32);
    bufp->chgBit(oldp+18,(vlSelfRef.Top__DOT__cpu__DOT__PCwrite));
    bufp->chgBit(oldp+19,(vlSelfRef.Top__DOT__cpu__DOT__IRwrite));
    bufp->chgBit(oldp+20,(vlSelfRef.Top__DOT__cpu__DOT__RegWrite));
    bufp->chgBit(oldp+21,(vlSelfRef.Top__DOT__cpu__DOT__AdrSrc));
    bufp->chgCData(oldp+22,(vlSelfRef.Top__DOT__cpu__DOT__ResultSrc),2);
    bufp->chgCData(oldp+23,(vlSelfRef.Top__DOT__cpu__DOT__SALUsrcA),2);
    bufp->chgCData(oldp+24,(vlSelfRef.Top__DOT__cpu__DOT__SALUsrcB),2);
    bufp->chgCData(oldp+25,(vlSelfRef.Top__DOT__cpu__DOT__ImmSrc),3);
    bufp->chgCData(oldp+26,(vlSelfRef.Top__DOT__cpu__DOT__ALUControl),4);
    bufp->chgBit(oldp+27,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__reset));
    bufp->chgBit(oldp+28,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__clk));
    bufp->chgBit(oldp+29,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__zero));
    bufp->chgIData(oldp+30,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__instruction),32);
    bufp->chgBit(oldp+31,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__PCwrite));
    bufp->chgBit(oldp+32,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__MemWrite));
    bufp->chgBit(oldp+33,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__IRwrite));
    bufp->chgBit(oldp+34,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__RegWrite));
    bufp->chgBit(oldp+35,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__AdrSrc));
    bufp->chgCData(oldp+36,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__ResultSrc),2);
    bufp->chgCData(oldp+37,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__SALUSrcA),2);
    bufp->chgCData(oldp+38,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__SALUSrcB),2);
    bufp->chgCData(oldp+39,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__ImmSrc),3);
    bufp->chgCData(oldp+40,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__ALUControl),4);
    bufp->chgCData(oldp+41,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__ALUop),2);
    bufp->chgBit(oldp+42,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__branch));
    bufp->chgIData(oldp+43,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__aluC_Generator__DOT__instruction),32);
    bufp->chgCData(oldp+44,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__aluC_Generator__DOT__ALUOp),2);
    bufp->chgCData(oldp+45,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__aluC_Generator__DOT__ALUControl),4);
    bufp->chgIData(oldp+46,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__decoder__DOT__instruction),32);
    bufp->chgCData(oldp+47,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__decoder__DOT__ExtOp),3);
    bufp->chgBit(oldp+48,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__fsm_inst__DOT__PCWrite));
    bufp->chgBit(oldp+49,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__fsm_inst__DOT__MemWrite));
    bufp->chgBit(oldp+50,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__fsm_inst__DOT__IRWrite));
    bufp->chgBit(oldp+51,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__fsm_inst__DOT__RegWrite));
    bufp->chgBit(oldp+52,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__fsm_inst__DOT__AdrSrc));
    bufp->chgCData(oldp+53,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__fsm_inst__DOT__ResultSrc),2);
    bufp->chgCData(oldp+54,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__fsm_inst__DOT__SALUSrcA),2);
    bufp->chgCData(oldp+55,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__fsm_inst__DOT__SALUSrcB),2);
    bufp->chgCData(oldp+56,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__fsm_inst__DOT__ALUCop),2);
    bufp->chgBit(oldp+57,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__fsm_inst__DOT__branch));
    bufp->chgBit(oldp+58,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__fsm_inst__DOT__clock));
    bufp->chgBit(oldp+59,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__fsm_inst__DOT__reset));
    bufp->chgBit(oldp+60,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__fsm_inst__DOT__zero));
    bufp->chgIData(oldp+61,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__fsm_inst__DOT__instruction),32);
    bufp->chgCData(oldp+62,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__fsm_inst__DOT__state),4);
    bufp->chgCData(oldp+63,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__fsm_inst__DOT__next_state),4);
    bufp->chgBit(oldp+64,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__clock));
    bufp->chgBit(oldp+65,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__reset));
    bufp->chgBit(oldp+66,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__PCWrite));
    bufp->chgBit(oldp+67,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__AdrSrc));
    bufp->chgBit(oldp+68,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__MemWrite));
    bufp->chgBit(oldp+69,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__IRWrite));
    bufp->chgBit(oldp+70,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__RegWrite));
    bufp->chgCData(oldp+71,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__ResultSrc),2);
    bufp->chgCData(oldp+72,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__ALUControl),4);
    bufp->chgCData(oldp+73,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__SALUsrcA),2);
    bufp->chgCData(oldp+74,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__SALUsrcB),2);
    bufp->chgCData(oldp+75,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__ImmSrc),3);
    bufp->chgIData(oldp+76,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__Instruction),32);
    bufp->chgBit(oldp+77,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__Zero));
    bufp->chgIData(oldp+78,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__MemAddr),32);
    bufp->chgIData(oldp+79,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__MemWriteData),32);
    bufp->chgCData(oldp+80,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__MemWriteMask),4);
    bufp->chgIData(oldp+81,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__MemReadData),32);
    bufp->chgIData(oldp+82,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__ALUResult),32);
    bufp->chgIData(oldp+83,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__Result_From_ResultSrc),32);
    bufp->chgIData(oldp+84,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__oldPC),32);
    bufp->chgIData(oldp+85,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__PC),32);
    bufp->chgIData(oldp+86,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__mdr_data),32);
    bufp->chgIData(oldp+87,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__rd1),32);
    bufp->chgIData(oldp+88,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__rd2),32);
    bufp->chgIData(oldp+89,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__imm),32);
    bufp->chgIData(oldp+90,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__ALUSrcA),32);
    bufp->chgIData(oldp+91,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__ALUSrcB),32);
    bufp->chgCData(oldp+92,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__alu__DOT__ALUControl),4);
    bufp->chgIData(oldp+93,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__alu__DOT__A),32);
    bufp->chgIData(oldp+94,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__alu__DOT__B),32);
    bufp->chgIData(oldp+95,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__alu__DOT__ALUResult),32);
    bufp->chgBit(oldp+96,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__alu__DOT__Zero));
    bufp->chgIData(oldp+97,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__extender__DOT__imm),32);
    bufp->chgCData(oldp+98,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__extender__DOT__ExtOp),3);
    bufp->chgIData(oldp+99,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__extender__DOT__extImm),32);
    bufp->chgBit(oldp+100,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__ir__DOT__reset));
    bufp->chgBit(oldp+101,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__ir__DOT__clock));
    bufp->chgBit(oldp+102,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__ir__DOT__IRWrite));
    bufp->chgIData(oldp+103,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__ir__DOT__instruction),32);
    bufp->chgIData(oldp+104,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__ir__DOT__PC),32);
    bufp->chgIData(oldp+105,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__ir__DOT__oldPC),32);
    bufp->chgIData(oldp+106,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__ir__DOT__o_instruction),32);
    bufp->chgBit(oldp+107,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__mdr__DOT__reset));
    bufp->chgBit(oldp+108,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__mdr__DOT__clock));
    bufp->chgCData(oldp+109,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__mdr__DOT__Which_load_comment),3);
    bufp->chgCData(oldp+110,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__mdr__DOT__What_HW_or_B),2);
    bufp->chgIData(oldp+111,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__mdr__DOT__Data),32);
    bufp->chgIData(oldp+112,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__mdr__DOT__o_Data),32);
    bufp->chgIData(oldp+113,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__mdr__DOT__i_Data),32);
    bufp->chgBit(oldp+114,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__clock));
    bufp->chgBit(oldp+115,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__reset));
    bufp->chgCData(oldp+116,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__rs1_addr),5);
    bufp->chgCData(oldp+117,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__rs2_addr),5);
    bufp->chgCData(oldp+118,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__rd_addr),5);
    bufp->chgIData(oldp+119,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__writeData),32);
    bufp->chgBit(oldp+120,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__RegWrite));
    bufp->chgIData(oldp+121,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__rs1_data),32);
    bufp->chgIData(oldp+122,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__rs2_data),32);
    bufp->chgIData(oldp+123,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[31]),32);
    bufp->chgIData(oldp+124,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[30]),32);
    bufp->chgIData(oldp+125,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[29]),32);
    bufp->chgIData(oldp+126,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[28]),32);
    bufp->chgIData(oldp+127,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[27]),32);
    bufp->chgIData(oldp+128,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[26]),32);
    bufp->chgIData(oldp+129,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[25]),32);
    bufp->chgIData(oldp+130,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[24]),32);
    bufp->chgIData(oldp+131,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[23]),32);
    bufp->chgIData(oldp+132,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[22]),32);
    bufp->chgIData(oldp+133,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[21]),32);
    bufp->chgIData(oldp+134,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[20]),32);
    bufp->chgIData(oldp+135,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[19]),32);
    bufp->chgIData(oldp+136,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[18]),32);
    bufp->chgIData(oldp+137,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[17]),32);
    bufp->chgIData(oldp+138,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[16]),32);
    bufp->chgIData(oldp+139,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[15]),32);
    bufp->chgIData(oldp+140,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[14]),32);
    bufp->chgIData(oldp+141,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[13]),32);
    bufp->chgIData(oldp+142,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[12]),32);
    bufp->chgIData(oldp+143,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[11]),32);
    bufp->chgIData(oldp+144,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[10]),32);
    bufp->chgIData(oldp+145,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[9]),32);
    bufp->chgIData(oldp+146,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[8]),32);
    bufp->chgIData(oldp+147,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[7]),32);
    bufp->chgIData(oldp+148,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[6]),32);
    bufp->chgIData(oldp+149,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[5]),32);
    bufp->chgIData(oldp+150,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[4]),32);
    bufp->chgIData(oldp+151,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[3]),32);
    bufp->chgIData(oldp+152,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[2]),32);
    bufp->chgIData(oldp+153,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[1]),32);
    bufp->chgIData(oldp+154,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[0]),32);
    bufp->chgBit(oldp+155,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__sResultSrc__DOT__clock));
    bufp->chgBit(oldp+156,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__sResultSrc__DOT__reset));
    bufp->chgCData(oldp+157,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__sResultSrc__DOT__resultSrc),2);
    bufp->chgIData(oldp+158,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__sResultSrc__DOT__ALUresult),32);
    bufp->chgIData(oldp+159,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__sResultSrc__DOT__MemData),32);
    bufp->chgIData(oldp+160,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__sResultSrc__DOT__Result),32);
    bufp->chgIData(oldp+161,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__sResultSrc__DOT__ALUout),32);
    bufp->chgBit(oldp+162,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__sdataSrc__DOT__clock));
    bufp->chgBit(oldp+163,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__sdataSrc__DOT__reset));
    bufp->chgIData(oldp+164,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__sdataSrc__DOT__newPC),32);
    bufp->chgIData(oldp+165,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__sdataSrc__DOT__oldPC),32);
    bufp->chgIData(oldp+166,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__sdataSrc__DOT__rs1),32);
    bufp->chgIData(oldp+167,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__sdataSrc__DOT__rs2),32);
    bufp->chgIData(oldp+168,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__sdataSrc__DOT__imm),32);
    bufp->chgCData(oldp+169,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__sdataSrc__DOT__SdataSrcA),2);
    bufp->chgCData(oldp+170,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__sdataSrc__DOT__SdataSrcB),2);
    bufp->chgIData(oldp+171,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__sdataSrc__DOT__ALUsrcA),32);
    bufp->chgIData(oldp+172,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__sdataSrc__DOT__ALUsrcB),32);
    bufp->chgIData(oldp+173,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__sdataSrc__DOT__Data1),32);
    bufp->chgIData(oldp+174,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__sdataSrc__DOT__writeData),32);
    bufp->chgBit(oldp+175,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__spcSrc__DOT__clk));
    bufp->chgBit(oldp+176,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__spcSrc__DOT__reset));
    bufp->chgBit(oldp+177,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__spcSrc__DOT__PCWrite));
    bufp->chgIData(oldp+178,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__spcSrc__DOT__newPC),32);
    bufp->chgIData(oldp+179,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__spcSrc__DOT__Result_From_ResultSrc),32);
    bufp->chgBit(oldp+180,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__spcSrc__DOT__Select));
    bufp->chgIData(oldp+181,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__spcSrc__DOT__PC),32);
    bufp->chgIData(oldp+182,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__spcSrc__DOT__MemAddr),32);
    bufp->chgIData(oldp+183,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__store__DOT__writeData),32);
    bufp->chgCData(oldp+184,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__store__DOT__WhichStore),3);
    bufp->chgCData(oldp+185,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__store__DOT__which_half_or_byte),2);
    bufp->chgIData(oldp+186,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__store__DOT__storeData),32);
    bufp->chgCData(oldp+187,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__store__DOT__storeMask),4);
    bufp->chgBit(oldp+188,(vlSelfRef.Top__DOT__memory__DOT__clk));
    bufp->chgBit(oldp+189,(vlSelfRef.Top__DOT__memory__DOT__memWrite));
    bufp->chgIData(oldp+190,(vlSelfRef.Top__DOT__memory__DOT__mem_addr),32);
    bufp->chgIData(oldp+191,(vlSelfRef.Top__DOT__memory__DOT__mem_wdata),32);
    bufp->chgCData(oldp+192,(vlSelfRef.Top__DOT__memory__DOT__mem_wmask),4);
    bufp->chgIData(oldp+193,(vlSelfRef.Top__DOT__memory__DOT__mem_rdata),32);
}

void Vtop___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_cleanup\n"); );
    // Locals
    VlUnpacked<CData/*0:0*/, 1> __Vm_traceActivity;
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        __Vm_traceActivity[__Vi0] = 0;
    }
    // Body
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    vlSymsp->__Vm_activity = false;
    __Vm_traceActivity[0U] = 0U;
}
