// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals

#include "verilated_vcd_c.h"
#include "Vtop__Syms.h"


VL_ATTR_COLD void Vtop___024root__trace_init_sub__TOP__0(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_sub__TOP__0\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    const int c = vlSymsp->__Vm_baseCode;
    VL_TRACE_PUSH_PREFIX(tracep, "$rootio", VerilatedTracePrefixType::SCOPE_MODULE, 0, 0);
    VL_TRACE_DECL_BIT(tracep,c+0,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BIT(tracep,c+1,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_POP_PREFIX(tracep);
    VL_TRACE_PUSH_PREFIX(tracep, "Top", VerilatedTracePrefixType::SCOPE_MODULE, 0, 0);
    VL_TRACE_DECL_BIT(tracep,c+2,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BIT(tracep,c+3,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BIT(tracep,c+4,0,"memWrite",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BUS(tracep,c+5,0,"mem_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BUS(tracep,c+6,0,"mem_wdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BUS(tracep,c+7,0,"mem_wmask",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, 3,0);
    VL_TRACE_DECL_BUS(tracep,c+8,0,"mem_rdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_PUSH_PREFIX(tracep, "cpu", VerilatedTracePrefixType::SCOPE_MODULE, 0, 0);
    VL_TRACE_DECL_BIT(tracep,c+9,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BIT(tracep,c+10,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BIT(tracep,c+11,0,"memWrite",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BUS(tracep,c+12,0,"mem_rdata",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BUS(tracep,c+13,0,"mem_addr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BUS(tracep,c+14,0,"mem_wdata",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BUS(tracep,c+15,0,"mem_wmask",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 3,0);
    VL_TRACE_DECL_BIT(tracep,c+16,0,"zero",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BUS(tracep,c+17,0,"instruction",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BIT(tracep,c+18,0,"PCwrite",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BIT(tracep,c+19,0,"IRwrite",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BIT(tracep,c+20,0,"RegWrite",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BIT(tracep,c+21,0,"AdrSrc",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BUS(tracep,c+22,0,"ResultSrc",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, 1,0);
    VL_TRACE_DECL_BUS(tracep,c+23,0,"SALUsrcA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, 1,0);
    VL_TRACE_DECL_BUS(tracep,c+24,0,"SALUsrcB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, 1,0);
    VL_TRACE_DECL_BUS(tracep,c+25,0,"ImmSrc",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, 2,0);
    VL_TRACE_DECL_BUS(tracep,c+26,0,"ALUControl",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, 3,0);
    VL_TRACE_PUSH_PREFIX(tracep, "controller", VerilatedTracePrefixType::SCOPE_MODULE, 0, 0);
    VL_TRACE_DECL_BIT(tracep,c+27,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BIT(tracep,c+28,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BIT(tracep,c+29,0,"zero",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BUS(tracep,c+30,0,"instruction",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BIT(tracep,c+31,0,"PCwrite",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BIT(tracep,c+32,0,"MemWrite",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BIT(tracep,c+33,0,"IRwrite",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BIT(tracep,c+34,0,"RegWrite",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BIT(tracep,c+35,0,"AdrSrc",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BUS(tracep,c+36,0,"ResultSrc",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 1,0);
    VL_TRACE_DECL_BUS(tracep,c+37,0,"SALUSrcA",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 1,0);
    VL_TRACE_DECL_BUS(tracep,c+38,0,"SALUSrcB",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 1,0);
    VL_TRACE_DECL_BUS(tracep,c+39,0,"ImmSrc",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 2,0);
    VL_TRACE_DECL_BUS(tracep,c+40,0,"ALUControl",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 3,0);
    VL_TRACE_DECL_BUS(tracep,c+41,0,"ALUop",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, 1,0);
    VL_TRACE_DECL_BIT(tracep,c+42,0,"branch",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC);
    VL_TRACE_PUSH_PREFIX(tracep, "aluC_Generator", VerilatedTracePrefixType::SCOPE_MODULE, 0, 0);
    VL_TRACE_DECL_BUS(tracep,c+43,0,"instruction",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BUS(tracep,c+44,0,"ALUOp",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 1,0);
    VL_TRACE_DECL_BUS(tracep,c+45,0,"ALUControl",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 3,0);
    VL_TRACE_POP_PREFIX(tracep);
    VL_TRACE_PUSH_PREFIX(tracep, "decoder", VerilatedTracePrefixType::SCOPE_MODULE, 0, 0);
    VL_TRACE_DECL_BUS(tracep,c+46,0,"instruction",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BUS(tracep,c+47,0,"ExtOp",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 2,0);
    VL_TRACE_POP_PREFIX(tracep);
    VL_TRACE_PUSH_PREFIX(tracep, "fsm_inst", VerilatedTracePrefixType::SCOPE_MODULE, 0, 0);
    VL_TRACE_DECL_BIT(tracep,c+48,0,"PCWrite",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BIT(tracep,c+49,0,"MemWrite",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BIT(tracep,c+50,0,"IRWrite",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BIT(tracep,c+51,0,"RegWrite",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BIT(tracep,c+52,0,"AdrSrc",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BUS(tracep,c+53,0,"ResultSrc",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 1,0);
    VL_TRACE_DECL_BUS(tracep,c+54,0,"SALUSrcA",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 1,0);
    VL_TRACE_DECL_BUS(tracep,c+55,0,"SALUSrcB",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 1,0);
    VL_TRACE_DECL_BUS(tracep,c+56,0,"ALUCop",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 1,0);
    VL_TRACE_DECL_BIT(tracep,c+57,0,"branch",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BIT(tracep,c+58,0,"clock",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BIT(tracep,c+59,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BIT(tracep,c+60,0,"zero",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BUS(tracep,c+61,0,"instruction",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BUS(tracep,c+194,0,"FETCH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, 3,0);
    VL_TRACE_DECL_BUS(tracep,c+195,0,"DECODE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, 3,0);
    VL_TRACE_DECL_BUS(tracep,c+196,0,"MEM_ADR",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, 3,0);
    VL_TRACE_DECL_BUS(tracep,c+197,0,"MEM_READ",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, 3,0);
    VL_TRACE_DECL_BUS(tracep,c+198,0,"MEM_WRITEBACK",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, 3,0);
    VL_TRACE_DECL_BUS(tracep,c+199,0,"MEM_WRITE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, 3,0);
    VL_TRACE_DECL_BUS(tracep,c+200,0,"EXECUTE_R",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, 3,0);
    VL_TRACE_DECL_BUS(tracep,c+201,0,"ALU_WRITEBACK",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, 3,0);
    VL_TRACE_DECL_BUS(tracep,c+202,0,"EXECUTE_I",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, 3,0);
    VL_TRACE_DECL_BUS(tracep,c+203,0,"JAL",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, 3,0);
    VL_TRACE_DECL_BUS(tracep,c+204,0,"BEQ",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, 3,0);
    VL_TRACE_DECL_BUS(tracep,c+205,0,"INIT",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, 3,0);
    VL_TRACE_DECL_BUS(tracep,c+206,0,"IDLE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, 3,0);
    VL_TRACE_DECL_BUS(tracep,c+62,0,"state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, 3,0);
    VL_TRACE_DECL_BUS(tracep,c+63,0,"next_state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, 3,0);
    VL_TRACE_POP_PREFIX(tracep);
    VL_TRACE_POP_PREFIX(tracep);
    VL_TRACE_PUSH_PREFIX(tracep, "datapath", VerilatedTracePrefixType::SCOPE_MODULE, 0, 0);
    VL_TRACE_DECL_BIT(tracep,c+64,0,"clock",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BIT(tracep,c+65,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BIT(tracep,c+66,0,"PCWrite",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BIT(tracep,c+67,0,"AdrSrc",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BIT(tracep,c+68,0,"MemWrite",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BIT(tracep,c+69,0,"IRWrite",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BIT(tracep,c+70,0,"RegWrite",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BUS(tracep,c+71,0,"ResultSrc",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 1,0);
    VL_TRACE_DECL_BUS(tracep,c+72,0,"ALUControl",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 3,0);
    VL_TRACE_DECL_BUS(tracep,c+73,0,"SALUsrcA",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 1,0);
    VL_TRACE_DECL_BUS(tracep,c+74,0,"SALUsrcB",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 1,0);
    VL_TRACE_DECL_BUS(tracep,c+75,0,"ImmSrc",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 2,0);
    VL_TRACE_DECL_BUS(tracep,c+76,0,"Instruction",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BIT(tracep,c+77,0,"Zero",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BUS(tracep,c+78,0,"MemAddr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BUS(tracep,c+79,0,"MemWriteData",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BUS(tracep,c+80,0,"MemWriteMask",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 3,0);
    VL_TRACE_DECL_BUS(tracep,c+81,0,"MemReadData",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BUS(tracep,c+82,0,"ALUResult",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BUS(tracep,c+83,0,"Result_From_ResultSrc",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BUS(tracep,c+84,0,"oldPC",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BUS(tracep,c+85,0,"PC",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BUS(tracep,c+86,0,"mdr_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BUS(tracep,c+87,0,"rd1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BUS(tracep,c+88,0,"rd2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BUS(tracep,c+89,0,"imm",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BUS(tracep,c+90,0,"ALUSrcA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BUS(tracep,c+91,0,"ALUSrcB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_PUSH_PREFIX(tracep, "alu", VerilatedTracePrefixType::SCOPE_MODULE, 0, 0);
    VL_TRACE_DECL_BUS(tracep,c+92,0,"ALUControl",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 3,0);
    VL_TRACE_DECL_BUS(tracep,c+93,0,"A",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BUS(tracep,c+94,0,"B",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BUS(tracep,c+95,0,"ALUResult",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BIT(tracep,c+96,0,"Zero",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_POP_PREFIX(tracep);
    VL_TRACE_PUSH_PREFIX(tracep, "extender", VerilatedTracePrefixType::SCOPE_MODULE, 0, 0);
    VL_TRACE_DECL_BUS(tracep,c+97,0,"imm",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BUS(tracep,c+98,0,"ExtOp",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 2,0);
    VL_TRACE_DECL_BUS(tracep,c+99,0,"extImm",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_POP_PREFIX(tracep);
    VL_TRACE_PUSH_PREFIX(tracep, "ir", VerilatedTracePrefixType::SCOPE_MODULE, 0, 0);
    VL_TRACE_DECL_BIT(tracep,c+100,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BIT(tracep,c+101,0,"clock",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BIT(tracep,c+102,0,"IRWrite",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BUS(tracep,c+103,0,"instruction",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BUS(tracep,c+104,0,"PC",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BUS(tracep,c+105,0,"oldPC",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BUS(tracep,c+106,0,"o_instruction",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_POP_PREFIX(tracep);
    VL_TRACE_PUSH_PREFIX(tracep, "mdr", VerilatedTracePrefixType::SCOPE_MODULE, 0, 0);
    VL_TRACE_DECL_BIT(tracep,c+107,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BIT(tracep,c+108,0,"clock",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BUS(tracep,c+109,0,"Which_load_comment",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 2,0);
    VL_TRACE_DECL_BUS(tracep,c+110,0,"What_HW_or_B",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 1,0);
    VL_TRACE_DECL_BUS(tracep,c+111,0,"Data",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BUS(tracep,c+112,0,"o_Data",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BUS(tracep,c+113,0,"i_Data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_POP_PREFIX(tracep);
    VL_TRACE_PUSH_PREFIX(tracep, "regFile", VerilatedTracePrefixType::SCOPE_MODULE, 0, 0);
    VL_TRACE_DECL_BIT(tracep,c+114,0,"clock",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BIT(tracep,c+115,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BUS(tracep,c+116,0,"rs1_addr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 4,0);
    VL_TRACE_DECL_BUS(tracep,c+117,0,"rs2_addr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 4,0);
    VL_TRACE_DECL_BUS(tracep,c+118,0,"rd_addr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 4,0);
    VL_TRACE_DECL_BUS(tracep,c+119,0,"writeData",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BIT(tracep,c+120,0,"RegWrite",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BUS(tracep,c+121,0,"rs1_data",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BUS(tracep,c+122,0,"rs2_data",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_PUSH_PREFIX(tracep, "regFile", VerilatedTracePrefixType::ARRAY_UNPACKED, 31, 0);
    for (int i = 0; i < 32; ++i) {
        VL_TRACE_DECL_BUS_ARRAY(tracep,c+123+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, (31 - i), 31,0);
    }
    VL_TRACE_POP_PREFIX(tracep);
    VL_TRACE_POP_PREFIX(tracep);
    VL_TRACE_PUSH_PREFIX(tracep, "sResultSrc", VerilatedTracePrefixType::SCOPE_MODULE, 0, 0);
    VL_TRACE_DECL_BIT(tracep,c+155,0,"clock",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BIT(tracep,c+156,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BUS(tracep,c+157,0,"resultSrc",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 1,0);
    VL_TRACE_DECL_BUS(tracep,c+158,0,"ALUresult",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BUS(tracep,c+159,0,"MemData",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BUS(tracep,c+160,0,"Result",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BUS(tracep,c+161,0,"ALUout",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_POP_PREFIX(tracep);
    VL_TRACE_PUSH_PREFIX(tracep, "sdataSrc", VerilatedTracePrefixType::SCOPE_MODULE, 0, 0);
    VL_TRACE_DECL_BIT(tracep,c+162,0,"clock",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BIT(tracep,c+163,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BUS(tracep,c+164,0,"newPC",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BUS(tracep,c+165,0,"oldPC",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BUS(tracep,c+166,0,"rs1",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BUS(tracep,c+167,0,"rs2",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BUS(tracep,c+168,0,"imm",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BUS(tracep,c+169,0,"SdataSrcA",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 1,0);
    VL_TRACE_DECL_BUS(tracep,c+170,0,"SdataSrcB",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 1,0);
    VL_TRACE_DECL_BUS(tracep,c+171,0,"ALUsrcA",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BUS(tracep,c+172,0,"ALUsrcB",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BUS(tracep,c+173,0,"Data1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BUS(tracep,c+174,0,"writeData",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_POP_PREFIX(tracep);
    VL_TRACE_PUSH_PREFIX(tracep, "spcSrc", VerilatedTracePrefixType::SCOPE_MODULE, 0, 0);
    VL_TRACE_DECL_BIT(tracep,c+175,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BIT(tracep,c+176,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BIT(tracep,c+177,0,"PCWrite",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BUS(tracep,c+178,0,"newPC",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BUS(tracep,c+179,0,"Result_From_ResultSrc",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BIT(tracep,c+180,0,"Select",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BUS(tracep,c+181,0,"PC",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BUS(tracep,c+182,0,"MemAddr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_POP_PREFIX(tracep);
    VL_TRACE_PUSH_PREFIX(tracep, "store", VerilatedTracePrefixType::SCOPE_MODULE, 0, 0);
    VL_TRACE_DECL_BUS(tracep,c+183,0,"writeData",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BUS(tracep,c+184,0,"WhichStore",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 2,0);
    VL_TRACE_DECL_BUS(tracep,c+185,0,"which_half_or_byte",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 1,0);
    VL_TRACE_DECL_BUS(tracep,c+186,0,"storeData",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BUS(tracep,c+187,0,"storeMask",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 3,0);
    VL_TRACE_POP_PREFIX(tracep);
    VL_TRACE_POP_PREFIX(tracep);
    VL_TRACE_POP_PREFIX(tracep);
    VL_TRACE_PUSH_PREFIX(tracep, "memory", VerilatedTracePrefixType::SCOPE_MODULE, 0, 0);
    VL_TRACE_DECL_BIT(tracep,c+188,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BIT(tracep,c+189,0,"memWrite",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC);
    VL_TRACE_DECL_BUS(tracep,c+190,0,"mem_addr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BUS(tracep,c+191,0,"mem_wdata",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_DECL_BUS(tracep,c+192,0,"mem_wmask",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 3,0);
    VL_TRACE_DECL_BUS(tracep,c+193,0,"mem_rdata",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, 31,0);
    VL_TRACE_POP_PREFIX(tracep);
    VL_TRACE_POP_PREFIX(tracep);
}

VL_ATTR_COLD void Vtop___024root__trace_init_dtype_sub____0(Vtop___024root* vlSelf, VerilatedVcd* tracep, const char* name, uint32_t fidx, uint32_t c, VerilatedTraceSigDirection direction);

VL_ATTR_COLD void Vtop___024root__trace_init_dtype____0(Vtop___024root* vlSelf, VerilatedVcd* tracep, const char* name, uint32_t fidx, uint32_t c, VerilatedTraceSigDirection direction) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_dtype____0\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    Vtop___024root__trace_init_dtype_sub____0(vlSelf, tracep, name, fidx, c, direction);
}

VL_ATTR_COLD void Vtop___024root__trace_init_dtype_sub____0(Vtop___024root* vlSelf, VerilatedVcd* tracep, const char* name, uint32_t fidx, uint32_t c, VerilatedTraceSigDirection direction) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_dtype_sub____0\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    VL_TRACE_PUSH_PREFIX(tracep, name, VerilatedTracePrefixType::ARRAY_UNPACKED, 31, 0);
    for (int i = 0; i < 32; ++i) {
        VL_TRACE_DECL_BUS_ARRAY(tracep,c+0+i*1,fidx,"",-1, direction, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, (31 - i), 31,0);
    }
    VL_TRACE_POP_PREFIX(tracep);
}

VL_ATTR_COLD void Vtop___024root__trace_init_top(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_top\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    Vtop___024root__trace_init_sub__TOP__0(vlSelf, tracep);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
VL_ATTR_COLD void Vtop___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vtop___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vtop___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/);

VL_ATTR_COLD void Vtop___024root__trace_register(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_register\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    tracep->addConstCb(&Vtop___024root__trace_const_0, 0, vlSelf);
    tracep->addFullCb(&Vtop___024root__trace_full_0, 0, vlSelf);
    tracep->addChgCb(&Vtop___024root__trace_chg_0, 0, vlSelf);
    tracep->addCleanupCb(&Vtop___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vtop___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_const_0\n"); );
    // Body
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    Vtop___024root__trace_const_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_const_0_sub_0\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    bufp->fullCData(oldp+194,(0U),4);
    bufp->fullCData(oldp+195,(1U),4);
    bufp->fullCData(oldp+196,(2U),4);
    bufp->fullCData(oldp+197,(3U),4);
    bufp->fullCData(oldp+198,(4U),4);
    bufp->fullCData(oldp+199,(5U),4);
    bufp->fullCData(oldp+200,(6U),4);
    bufp->fullCData(oldp+201,(7U),4);
    bufp->fullCData(oldp+202,(8U),4);
    bufp->fullCData(oldp+203,(9U),4);
    bufp->fullCData(oldp+204,(0x0aU),4);
    bufp->fullCData(oldp+205,(0x0eU),4);
    bufp->fullCData(oldp+206,(0x0fU),4);
}

VL_ATTR_COLD void Vtop___024root__trace_full_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vtop___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_0\n"); );
    // Body
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    Vtop___024root__trace_full_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtop___024root__trace_full_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_0_sub_0\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    bufp->fullBit(oldp+0,(vlSelfRef.clk));
    bufp->fullBit(oldp+1,(vlSelfRef.reset));
    bufp->fullBit(oldp+2,(vlSelfRef.Top__DOT__clk));
    bufp->fullBit(oldp+3,(vlSelfRef.Top__DOT__reset));
    bufp->fullBit(oldp+4,(vlSelfRef.Top__DOT__memWrite));
    bufp->fullIData(oldp+5,(vlSelfRef.Top__DOT__mem_addr),32);
    bufp->fullIData(oldp+6,(vlSelfRef.Top__DOT__mem_wdata),32);
    bufp->fullCData(oldp+7,(vlSelfRef.Top__DOT__mem_wmask),4);
    bufp->fullIData(oldp+8,(vlSelfRef.Top__DOT__mem_rdata),32);
    bufp->fullBit(oldp+9,(vlSelfRef.Top__DOT__cpu__DOT__clk));
    bufp->fullBit(oldp+10,(vlSelfRef.Top__DOT__cpu__DOT__reset));
    bufp->fullBit(oldp+11,(vlSelfRef.Top__DOT__cpu__DOT__memWrite));
    bufp->fullIData(oldp+12,(vlSelfRef.Top__DOT__cpu__DOT__mem_rdata),32);
    bufp->fullIData(oldp+13,(vlSelfRef.Top__DOT__cpu__DOT__mem_addr),32);
    bufp->fullIData(oldp+14,(vlSelfRef.Top__DOT__cpu__DOT__mem_wdata),32);
    bufp->fullCData(oldp+15,(vlSelfRef.Top__DOT__cpu__DOT__mem_wmask),4);
    bufp->fullBit(oldp+16,(vlSelfRef.Top__DOT__cpu__DOT__zero));
    bufp->fullIData(oldp+17,(vlSelfRef.Top__DOT__cpu__DOT__instruction),32);
    bufp->fullBit(oldp+18,(vlSelfRef.Top__DOT__cpu__DOT__PCwrite));
    bufp->fullBit(oldp+19,(vlSelfRef.Top__DOT__cpu__DOT__IRwrite));
    bufp->fullBit(oldp+20,(vlSelfRef.Top__DOT__cpu__DOT__RegWrite));
    bufp->fullBit(oldp+21,(vlSelfRef.Top__DOT__cpu__DOT__AdrSrc));
    bufp->fullCData(oldp+22,(vlSelfRef.Top__DOT__cpu__DOT__ResultSrc),2);
    bufp->fullCData(oldp+23,(vlSelfRef.Top__DOT__cpu__DOT__SALUsrcA),2);
    bufp->fullCData(oldp+24,(vlSelfRef.Top__DOT__cpu__DOT__SALUsrcB),2);
    bufp->fullCData(oldp+25,(vlSelfRef.Top__DOT__cpu__DOT__ImmSrc),3);
    bufp->fullCData(oldp+26,(vlSelfRef.Top__DOT__cpu__DOT__ALUControl),4);
    bufp->fullBit(oldp+27,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__reset));
    bufp->fullBit(oldp+28,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__clk));
    bufp->fullBit(oldp+29,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__zero));
    bufp->fullIData(oldp+30,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__instruction),32);
    bufp->fullBit(oldp+31,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__PCwrite));
    bufp->fullBit(oldp+32,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__MemWrite));
    bufp->fullBit(oldp+33,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__IRwrite));
    bufp->fullBit(oldp+34,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__RegWrite));
    bufp->fullBit(oldp+35,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__AdrSrc));
    bufp->fullCData(oldp+36,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__ResultSrc),2);
    bufp->fullCData(oldp+37,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__SALUSrcA),2);
    bufp->fullCData(oldp+38,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__SALUSrcB),2);
    bufp->fullCData(oldp+39,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__ImmSrc),3);
    bufp->fullCData(oldp+40,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__ALUControl),4);
    bufp->fullCData(oldp+41,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__ALUop),2);
    bufp->fullBit(oldp+42,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__branch));
    bufp->fullIData(oldp+43,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__aluC_Generator__DOT__instruction),32);
    bufp->fullCData(oldp+44,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__aluC_Generator__DOT__ALUOp),2);
    bufp->fullCData(oldp+45,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__aluC_Generator__DOT__ALUControl),4);
    bufp->fullIData(oldp+46,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__decoder__DOT__instruction),32);
    bufp->fullCData(oldp+47,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__decoder__DOT__ExtOp),3);
    bufp->fullBit(oldp+48,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__fsm_inst__DOT__PCWrite));
    bufp->fullBit(oldp+49,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__fsm_inst__DOT__MemWrite));
    bufp->fullBit(oldp+50,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__fsm_inst__DOT__IRWrite));
    bufp->fullBit(oldp+51,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__fsm_inst__DOT__RegWrite));
    bufp->fullBit(oldp+52,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__fsm_inst__DOT__AdrSrc));
    bufp->fullCData(oldp+53,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__fsm_inst__DOT__ResultSrc),2);
    bufp->fullCData(oldp+54,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__fsm_inst__DOT__SALUSrcA),2);
    bufp->fullCData(oldp+55,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__fsm_inst__DOT__SALUSrcB),2);
    bufp->fullCData(oldp+56,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__fsm_inst__DOT__ALUCop),2);
    bufp->fullBit(oldp+57,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__fsm_inst__DOT__branch));
    bufp->fullBit(oldp+58,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__fsm_inst__DOT__clock));
    bufp->fullBit(oldp+59,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__fsm_inst__DOT__reset));
    bufp->fullBit(oldp+60,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__fsm_inst__DOT__zero));
    bufp->fullIData(oldp+61,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__fsm_inst__DOT__instruction),32);
    bufp->fullCData(oldp+62,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__fsm_inst__DOT__state),4);
    bufp->fullCData(oldp+63,(vlSelfRef.Top__DOT__cpu__DOT__controller__DOT__fsm_inst__DOT__next_state),4);
    bufp->fullBit(oldp+64,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__clock));
    bufp->fullBit(oldp+65,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__reset));
    bufp->fullBit(oldp+66,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__PCWrite));
    bufp->fullBit(oldp+67,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__AdrSrc));
    bufp->fullBit(oldp+68,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__MemWrite));
    bufp->fullBit(oldp+69,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__IRWrite));
    bufp->fullBit(oldp+70,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__RegWrite));
    bufp->fullCData(oldp+71,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__ResultSrc),2);
    bufp->fullCData(oldp+72,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__ALUControl),4);
    bufp->fullCData(oldp+73,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__SALUsrcA),2);
    bufp->fullCData(oldp+74,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__SALUsrcB),2);
    bufp->fullCData(oldp+75,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__ImmSrc),3);
    bufp->fullIData(oldp+76,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__Instruction),32);
    bufp->fullBit(oldp+77,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__Zero));
    bufp->fullIData(oldp+78,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__MemAddr),32);
    bufp->fullIData(oldp+79,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__MemWriteData),32);
    bufp->fullCData(oldp+80,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__MemWriteMask),4);
    bufp->fullIData(oldp+81,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__MemReadData),32);
    bufp->fullIData(oldp+82,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__ALUResult),32);
    bufp->fullIData(oldp+83,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__Result_From_ResultSrc),32);
    bufp->fullIData(oldp+84,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__oldPC),32);
    bufp->fullIData(oldp+85,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__PC),32);
    bufp->fullIData(oldp+86,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__mdr_data),32);
    bufp->fullIData(oldp+87,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__rd1),32);
    bufp->fullIData(oldp+88,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__rd2),32);
    bufp->fullIData(oldp+89,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__imm),32);
    bufp->fullIData(oldp+90,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__ALUSrcA),32);
    bufp->fullIData(oldp+91,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__ALUSrcB),32);
    bufp->fullCData(oldp+92,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__alu__DOT__ALUControl),4);
    bufp->fullIData(oldp+93,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__alu__DOT__A),32);
    bufp->fullIData(oldp+94,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__alu__DOT__B),32);
    bufp->fullIData(oldp+95,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__alu__DOT__ALUResult),32);
    bufp->fullBit(oldp+96,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__alu__DOT__Zero));
    bufp->fullIData(oldp+97,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__extender__DOT__imm),32);
    bufp->fullCData(oldp+98,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__extender__DOT__ExtOp),3);
    bufp->fullIData(oldp+99,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__extender__DOT__extImm),32);
    bufp->fullBit(oldp+100,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__ir__DOT__reset));
    bufp->fullBit(oldp+101,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__ir__DOT__clock));
    bufp->fullBit(oldp+102,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__ir__DOT__IRWrite));
    bufp->fullIData(oldp+103,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__ir__DOT__instruction),32);
    bufp->fullIData(oldp+104,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__ir__DOT__PC),32);
    bufp->fullIData(oldp+105,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__ir__DOT__oldPC),32);
    bufp->fullIData(oldp+106,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__ir__DOT__o_instruction),32);
    bufp->fullBit(oldp+107,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__mdr__DOT__reset));
    bufp->fullBit(oldp+108,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__mdr__DOT__clock));
    bufp->fullCData(oldp+109,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__mdr__DOT__Which_load_comment),3);
    bufp->fullCData(oldp+110,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__mdr__DOT__What_HW_or_B),2);
    bufp->fullIData(oldp+111,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__mdr__DOT__Data),32);
    bufp->fullIData(oldp+112,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__mdr__DOT__o_Data),32);
    bufp->fullIData(oldp+113,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__mdr__DOT__i_Data),32);
    bufp->fullBit(oldp+114,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__clock));
    bufp->fullBit(oldp+115,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__reset));
    bufp->fullCData(oldp+116,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__rs1_addr),5);
    bufp->fullCData(oldp+117,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__rs2_addr),5);
    bufp->fullCData(oldp+118,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__rd_addr),5);
    bufp->fullIData(oldp+119,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__writeData),32);
    bufp->fullBit(oldp+120,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__RegWrite));
    bufp->fullIData(oldp+121,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__rs1_data),32);
    bufp->fullIData(oldp+122,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__rs2_data),32);
    bufp->fullIData(oldp+123,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[31]),32);
    bufp->fullIData(oldp+124,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[30]),32);
    bufp->fullIData(oldp+125,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[29]),32);
    bufp->fullIData(oldp+126,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[28]),32);
    bufp->fullIData(oldp+127,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[27]),32);
    bufp->fullIData(oldp+128,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[26]),32);
    bufp->fullIData(oldp+129,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[25]),32);
    bufp->fullIData(oldp+130,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[24]),32);
    bufp->fullIData(oldp+131,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[23]),32);
    bufp->fullIData(oldp+132,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[22]),32);
    bufp->fullIData(oldp+133,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[21]),32);
    bufp->fullIData(oldp+134,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[20]),32);
    bufp->fullIData(oldp+135,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[19]),32);
    bufp->fullIData(oldp+136,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[18]),32);
    bufp->fullIData(oldp+137,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[17]),32);
    bufp->fullIData(oldp+138,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[16]),32);
    bufp->fullIData(oldp+139,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[15]),32);
    bufp->fullIData(oldp+140,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[14]),32);
    bufp->fullIData(oldp+141,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[13]),32);
    bufp->fullIData(oldp+142,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[12]),32);
    bufp->fullIData(oldp+143,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[11]),32);
    bufp->fullIData(oldp+144,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[10]),32);
    bufp->fullIData(oldp+145,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[9]),32);
    bufp->fullIData(oldp+146,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[8]),32);
    bufp->fullIData(oldp+147,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[7]),32);
    bufp->fullIData(oldp+148,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[6]),32);
    bufp->fullIData(oldp+149,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[5]),32);
    bufp->fullIData(oldp+150,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[4]),32);
    bufp->fullIData(oldp+151,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[3]),32);
    bufp->fullIData(oldp+152,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[2]),32);
    bufp->fullIData(oldp+153,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[1]),32);
    bufp->fullIData(oldp+154,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__regFile__DOT__regFile[0]),32);
    bufp->fullBit(oldp+155,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__sResultSrc__DOT__clock));
    bufp->fullBit(oldp+156,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__sResultSrc__DOT__reset));
    bufp->fullCData(oldp+157,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__sResultSrc__DOT__resultSrc),2);
    bufp->fullIData(oldp+158,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__sResultSrc__DOT__ALUresult),32);
    bufp->fullIData(oldp+159,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__sResultSrc__DOT__MemData),32);
    bufp->fullIData(oldp+160,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__sResultSrc__DOT__Result),32);
    bufp->fullIData(oldp+161,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__sResultSrc__DOT__ALUout),32);
    bufp->fullBit(oldp+162,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__sdataSrc__DOT__clock));
    bufp->fullBit(oldp+163,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__sdataSrc__DOT__reset));
    bufp->fullIData(oldp+164,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__sdataSrc__DOT__newPC),32);
    bufp->fullIData(oldp+165,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__sdataSrc__DOT__oldPC),32);
    bufp->fullIData(oldp+166,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__sdataSrc__DOT__rs1),32);
    bufp->fullIData(oldp+167,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__sdataSrc__DOT__rs2),32);
    bufp->fullIData(oldp+168,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__sdataSrc__DOT__imm),32);
    bufp->fullCData(oldp+169,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__sdataSrc__DOT__SdataSrcA),2);
    bufp->fullCData(oldp+170,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__sdataSrc__DOT__SdataSrcB),2);
    bufp->fullIData(oldp+171,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__sdataSrc__DOT__ALUsrcA),32);
    bufp->fullIData(oldp+172,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__sdataSrc__DOT__ALUsrcB),32);
    bufp->fullIData(oldp+173,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__sdataSrc__DOT__Data1),32);
    bufp->fullIData(oldp+174,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__sdataSrc__DOT__writeData),32);
    bufp->fullBit(oldp+175,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__spcSrc__DOT__clk));
    bufp->fullBit(oldp+176,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__spcSrc__DOT__reset));
    bufp->fullBit(oldp+177,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__spcSrc__DOT__PCWrite));
    bufp->fullIData(oldp+178,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__spcSrc__DOT__newPC),32);
    bufp->fullIData(oldp+179,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__spcSrc__DOT__Result_From_ResultSrc),32);
    bufp->fullBit(oldp+180,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__spcSrc__DOT__Select));
    bufp->fullIData(oldp+181,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__spcSrc__DOT__PC),32);
    bufp->fullIData(oldp+182,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__spcSrc__DOT__MemAddr),32);
    bufp->fullIData(oldp+183,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__store__DOT__writeData),32);
    bufp->fullCData(oldp+184,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__store__DOT__WhichStore),3);
    bufp->fullCData(oldp+185,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__store__DOT__which_half_or_byte),2);
    bufp->fullIData(oldp+186,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__store__DOT__storeData),32);
    bufp->fullCData(oldp+187,(vlSelfRef.Top__DOT__cpu__DOT__datapath__DOT__store__DOT__storeMask),4);
    bufp->fullBit(oldp+188,(vlSelfRef.Top__DOT__memory__DOT__clk));
    bufp->fullBit(oldp+189,(vlSelfRef.Top__DOT__memory__DOT__memWrite));
    bufp->fullIData(oldp+190,(vlSelfRef.Top__DOT__memory__DOT__mem_addr),32);
    bufp->fullIData(oldp+191,(vlSelfRef.Top__DOT__memory__DOT__mem_wdata),32);
    bufp->fullCData(oldp+192,(vlSelfRef.Top__DOT__memory__DOT__mem_wmask),4);
    bufp->fullIData(oldp+193,(vlSelfRef.Top__DOT__memory__DOT__mem_rdata),32);
}
